In [4]:
import pandas as pd
import numpy as np

data = {
    '이름' : ['유재석', '박명수', '정준하', '노홍철', '정형돈', '하하'],
    '지역' : ['서울', '부산', '부산', '서울', '서울', '서울'],
    '나이' : [19, 23, 20, 25, 18, 21],
    '국어점수' : [86, 90, 80, 65, 50, 60],
    '수학점수' : [86, 100, 66, 70, 40, 80],
    '코딩' : ['Python', 'Java', np.nan, 'Javascript', 'PYTHON', np.nan]
}
df = pd.DataFrame(data=data,index=['1번','2번','3번','4번','5번','6번'])
print(df)
# df.info()

     이름  지역  나이  국어점수  수학점수          코딩
1번  유재석  서울  19    86    86      Python
2번  박명수  부산  23    90   100        Java
3번  정준하  부산  20    80    66         NaN
4번  노홍철  서울  25    65    70  Javascript
5번  정형돈  서울  18    50    40      PYTHON
6번   하하  서울  21    60    80         NaN

In [5]:
# 컬럼 내용 수정
df['지역'].replace({"서울":"경기","부산":"대구"},replace=True)
print(df)

TypeError: NDFrame.replace() got an unexpected keyword argument 'replace'

In [ ]:
#대소문자가 섞여있는 '코딩'컬럼을 모두 소문자로 바꾸고 싶음
#해당 열이 문자열(str)일 경우, 문자열 관련 메서드를 적용할 수있게 해줌

df['코딩'] = df['코딩'].str.lower()
df

     이름  지역  나이  국어점수  수학점수          코딩
1번  유재석  서울  19    86    86      python
2번  박명수  부산  23    90   100        java
3번  정준하  부산  20    80    66         NaN
4번  노홍철  서울  25    65    70  javascript
5번  정형돈  서울  18    50    40      python
6번   하하  서울  21    60    80         NaN

In [ ]:
# 대소문자가 섞여있는 '코딩' 컬럼을 모두 대문자로 바꾸고 싶음
df['코딩'] = df['코딩'].str.upper()
df.info()

<class 'pandas.DataFrame'>
Index: 6 entries, 1번 to 6번
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      6 non-null      str
 1   지역      6 non-null      str
 2   나이      6 non-null      int64
 3   국어점수    6 non-null      int64
 4   수학점수    6 non-null      int64
 5   코딩      4 non-null      str
 6   점수종합    6 non-null      int64
 7   결과      2 non-null      str
dtypes: int64(4), str(4)
memory usage: 604.0+ bytes

In [ ]:
df['국어점수'] = df['국어점수'] + 5
df

     이름  지역  나이  국어점수  수학점수          코딩
1번  유재석  서울  19    91    86      PYTHON
2번  박명수  부산  23    95   100        JAVA
3번  정준하  부산  20    85    66         NaN
4번  노홍철  서울  25    70    70  JAVASCRIPT
5번  정형돈  서울  18    55    40      PYTHON
6번   하하  서울  21    65    80         NaN

In [53]:
#컬럼 추가
# 없으면 추가, 있으면 해당 값 업데이트

# 점수종합 컬럽에는 국어점수 + 수학점수가 들어 가도록 하시오.

df["점수종합"] = df["국어점수"] + df["수학점수"]
df

     이름  지역  나이  국어점수  수학점수          코딩   결과  점수종합
1번  유재석  서울  19    86    86      Python   합격   172
2번  박명수  부산  23    90   100        Java   합격   190
3번  정준하  부산  20    80    66         NaN  NaN   146
4번  노홍철  서울  25    65    70  Javascript  NaN   135
5번  정형돈  서울  18    50    40      PYTHON  NaN    90
6번   하하  서울  21    60    80         NaN  NaN   140

In [ ]:
# 결과 컬럼 생성, 불합격으로 전부 초기화 하시오

# df["결과"] = "불합격"
# df

In [54]:
# 점수 총합이 160점을 넘으면 , 결과 컬럼에 "합격
print(df[ df['점수종합'] >160])
df.loc[ df['점수종합'] > 160, '결과'] = '합격' # loc 에도 불리언 인덱싱은 행을 선택할수있는 iloc가올수있다
df

     이름  지역  나이  국어점수  수학점수      코딩  결과  점수종합
1번  유재석  서울  19    86    86  Python  합격   172
2번  박명수  부산  23    90   100    Java  합격   190

     이름  지역  나이  국어점수  수학점수          코딩   결과  점수종합
1번  유재석  서울  19    86    86      Python   합격   172
2번  박명수  부산  23    90   100        Java   합격   190
3번  정준하  부산  20    80    66         NaN  NaN   146
4번  노홍철  서울  25    65    70  Javascript  NaN   135
5번  정형돈  서울  18    50    40      PYTHON  NaN    90
6번   하하  서울  21    60    80         NaN  NaN   140

In [55]:
# 컬럼 삭제 
df.drop(columns=["점수종합"],inplace=True)
print(df)

     이름  지역  나이  국어점수  수학점수          코딩   결과
1번  유재석  서울  19    86    86      Python   합격
2번  박명수  부산  23    90   100        Java   합격
3번  정준하  부산  20    80    66         NaN  NaN
4번  노홍철  서울  25    65    70  Javascript  NaN
5번  정형돈  서울  18    50    40      PYTHON  NaN
6번   하하  서울  21    60    80         NaN  NaN

In [56]:
df.drop(columns=["결과"],inplace=True)
print(df)

     이름  지역  나이  국어점수  수학점수          코딩
1번  유재석  서울  19    86    86      Python
2번  박명수  부산  23    90   100        Java
3번  정준하  부산  20    80    66         NaN
4번  노홍철  서울  25    65    70  Javascript
5번  정형돈  서울  18    50    40      PYTHON
6번   하하  서울  21    60    80         NaN

In [58]:
# 행단위 CRUD

# 행추가

df.loc["7번"] = ["길", "부산", 22, 90, 80, "java"]
df

     이름  지역  나이  국어점수  수학점수          코딩
1번  유재석  서울  19    86    86      Python
2번  박명수  부산  23    90   100        Java
3번  정준하  부산  20    80    66         NaN
4번  노홍철  서울  25    65    70  Javascript
5번  정형돈  서울  18    50    40      PYTHON
6번   하하  서울  21    60    80         NaN
7번    길  부산  22    90    80        java

In [59]:
# 셀수정
df.loc['4번','국어점수'] = 90
df

     이름  지역  나이  국어점수  수학점수          코딩
1번  유재석  서울  19    86    86      Python
2번  박명수  부산  23    90   100        Java
3번  정준하  부산  20    80    66         NaN
4번  노홍철  서울  25    90    70  Javascript
5번  정형돈  서울  18    50    40      PYTHON
6번   하하  서울  21    60    80         NaN
7번    길  부산  22    90    80        java

In [61]:
# 두개 이상의 행의 값을 변경 할떄
df.loc['4번',["지역","코딩"]] = ["대구","python"]
df

     이름  지역  나이  국어점수  수학점수      코딩
1번  유재석  서울  19    86    86  Python
2번  박명수  부산  23    90   100    Java
3번  정준하  부산  20    80    66     NaN
4번  노홍철  대구  25    90    70  python
5번  정형돈  서울  18    50    40  PYTHON
6번   하하  서울  21    60    80     NaN
7번    길  부산  22    90    80    java

In [64]:
df.loc['1번',["나이","지역"]] = [20,"광주"]
df

     이름  지역  나이  국어점수  수학점수      코딩
1번  유재석  광주  20    86    86  Python
2번  박명수  부산  23    90   100    Java
3번  정준하  부산  20    80    66     NaN
4번  노홍철  대구  25    90    70  python
5번  정형돈  서울  18    50    40  PYTHON
6번   하하  서울  21    60    80     NaN
7번    길  부산  22    90    80    java